# Generated by Django 4.1.3 on 2022-11-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('name', models.CharField(max_length=150)),
                ('is_gaming', models.BooleanField(default=False)),
                ('processor', models.TextField()),
                ('graphic_card', models.TextField()),
                ('ram', models.IntegerField()),
                ('os', models.BooleanField(default=False)),
            ],
        ),
    ]
