# Generated by Django 4.1.3 on 2022-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
