# Generated by Django 4.1.3 on 2022-11-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop_shop', '0002_laptop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
